# Generated by Django 5.0.2 on 2024-02-14 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("admin_user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MechanicModel",
            fields=[
                (
                    "mechanic_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="admin_user.mechanic",
                    ),
                ),
            ],
            bases=("admin_user.mechanic",),
        ),
    ]
