# Generated by Django 5.0.3 on 2024-04-20 08:06

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("admin_user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admin_user.attendance",),
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admin_user.feedback",),
        ),
        migrations.CreateModel(
            name="Mechanic",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admin_user.mechanic",),
        ),
        migrations.CreateModel(
            name="Request",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admin_user.request",),
        ),
    ]
