# Generated by Django 5.0.2 on 2024-02-14 10:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_user", "0001_initial"),
        ("mechanic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceModel",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admin_user.attendance",),
        ),
        migrations.CreateModel(
            name="FeedbackModel",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admin_user.feedback",),
        ),
        migrations.CreateModel(
            name="RequestModel",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admin_user.request",),
        ),
        migrations.DeleteModel(
            name="MechanicModel",
        ),
        migrations.CreateModel(
            name="MechanicModel",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admin_user.mechanic",),
        ),
    ]
