# Generated by Django 5.0.2 on 2024-03-23 13:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_user", "0001_initial"),
        ("mechanic", "0002_attendancemodel_feedbackmodel_requestmodel_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AttendanceModel",
        ),
        migrations.DeleteModel(
            name="FeedbackModel",
        ),
        migrations.DeleteModel(
            name="MechanicModel",
        ),
        migrations.DeleteModel(
            name="RequestModel",
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admin_user.attendance",),
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admin_user.feedback",),
        ),
        migrations.CreateModel(
            name="Mechanic",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admin_user.mechanic",),
        ),
        migrations.CreateModel(
            name="Request",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admin_user.request",),
        ),
    ]
